### ISSUE TITLE
Bugs for using find_lr_path(), dec_cci(), and dec_cci_all()

### ISSUE THREAD

**Issue by dongyuanwu** [ZJUFanLab/SpaTalk#15]
Hi,

I tried to skip the decomposition step and directly inferred the cell-cell communications. But I always met the same errors for `find_lr_path()`, `dec_cci()`, and `dec_cci_all()`:

```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'rowSums': 'data' must be of a vector type, was 'NULL'
```

I was back to review the code and found that when running `.get_st_data()` in these functions and the ST type was not single-cell, the code is
```
st_data <- object@data$newdata
st_meta <- object@meta$newmeta
```
However, the object doesn't contain `newdata` and `newmeta`. They should be `rawdata` and `rawmeta`. I explored further and found that `newdata` and `newmeta` will only be created when using `dec_celltype()`.

In addition to the above bug, there is another bug related to spot-based ST data: In the `.get_cellpair()` function, there are several lines to call `cell_sender$cell` or `cell_receiver$cell`. For example:
```
celltype_dist1 <- celltype_dist[, cell_sender$cell[j]]
```
Based on the description of the `createSpaTalk ()` function, the column name of spot-based ST data should be "spot" instead of "cell". The different names will cause errors for `dec_cci()` and `dec_cci_all()`.

Right now the code works for me because I fixed it by myself. But I suggest adding suitable if-else statements into the related functions and checking these different conditions carefully.

**Comment by multitalk** [comment]
Thanks for your feedback. In fact, our initial purpose is to skip the decomposition step and directly inferred the cell-cell communications for some single-cell ST data with known cell types rather than spot-based ST data. But yes, there is a scenario that users may want to directly infer the cell-cell communications with known cell types for spot-based ST data such as Slide-seq data which approaches single-cell resolution. So I have fixed the bugs considering this situation. Thank you again for your suggestions.
