### ISSUE TITLE
Where to find the root squared of both intra-cellular and inter-cellular score ?

### ISSUE THREAD

**Issue by ZheFrench** [ZJUFanLab/SpaTalk#16]
It's more a set of questions than a bug report.

I was wondering if the `score` in `obj@lrpair`  provided after `find_lr_path` & `dec_cci_all` was the intra-cellular score, the inter-cellular or the final one as the root squared of both. 
Just to know if at this point you were already taking account of the TF, targets genes.  The p-palue seems only base on the LR co-expression, right ? So that would mean it's only the inter-cellular score.

So score in `obj@tf` is probably the intra-cellular score ? but both scores are not yet mixed to rank the interaction ? So it's needed to apply `get_lr_path`.

 `get_lr_path` gives  p-value for pathways based on Fisher for specific L/R , Sender/Receiver. but also the final score ? 

I'd like to know where to set my p-val cutoff for filtering LR but want miss the fact that is you are taking account of downstream genes...I don't know if you see my point.

```
obj <- createSpaTalk(st_data = counts,
                     st_meta = areas[,c("cell","x","y")],
                     species = "Human",
                     if_st_is_sc = T,
                     spot_max_cell = 1,
                     celltype = areas$cell_type)

obj <- find_lr_path(object = obj , lrpairs = lrpairs, pathways = pathways,if_doParallel = T,use_n_cores=32)
obj <- dec_cci_all(object = obj,if_doParallel = T,use_n_cores=32)
```

I was wondering if it's necessary to do a loop to compute all the final root squared product of intra/inter scores for all LR provided by get_lr_path.

```
datalist.pval    = list()
datalist.tf_path = list()

for (i in 1:dim(obj@lrpair)[1]) {

print("### Call get_lr_path for each pair")
print(i)
print(dim(obj@lrpair)[1])

    # Get LR and downstream pathways
    obj_lr_path <- get_lr_path(object = obj,
                               celltype_sender = obj@lrpair[i,c("celltype_sender")],
                               celltype_receiver = obj@lrpair[i,c("celltype_receiver")],
                               ligand = obj@lrpair[i,c("ligand")],
                               receptor = obj@lrpair[i,c("receptor")])

     datalist.pval[[i]] <- obj_lr_path$path_pvalue # add it to your list
     datalist.tf_path[[i]] <- obj_lr_path$tf_path # add it to your list

}

big_data.pval <- do.call(rbind, datalist.pval)
big_data.tf <- do.call(rbind, datalist.tf_path)

write.table(big_data.pval, glue("lrpath.pvalue.tsv"), col.names = TRUE, row.names = FALSE, sep="\t", quote=FALSE)
write.table(big_data.tf, glue("lrpath.tf_path.tsv"), col.names = TRUE, row.names = FALSE, sep="\t", quote=FALSE)
```

Last question, is that possible to use SPATALK for the whole spatial transcriptomics setting for all cells two clusters. Imagine you have any appriori over the cell type / clusters.  One cell would have both cluster1 / cluster2 anotations and so every cells would be compared.
Is this working ? 

Great job you have done here by the way. 
Thanks.

**Comment by multitalk** [comment]
@ZheFrench Thanks for your careful review and feedback.
- The `score` in `obj@lrpair` provided after `find_lr_path` & `dec_cci_all` is the final score by combing the inter- and intra- scores, and the `score` in `obj@tf` is the intra-cellular score. 
- Given the output generated from `get_lr_path`, the `tf_path` means the inferred ligand-receptor-target signaling network and the `path_pvalue` means the significance of enriched pathways with the inferred ligand-receptor-target signaling network nodes using the fisher-exact test. In fact, the inferred ligand-receptor-target signaling network is too large for all sender-receiver pairs, so I design the `get_lr_path` for users to get the inferred ligand-receptor-target signaling network for a given sender-receiver pair instead of storing it into the `SpaTalk object`.
- It might not be possible to use SpaTalk for the whole spatial transcriptomics setting for all cells two clusters because the distance of two cluster cells is equal to the that of all cells. In this condition, it is hard to determine if the two clusters are spatially proximal or not. I suggest spatial transcriptomics with more clusters.
